import {
    MapAttributionControl,
    MapDragRotateAndZoomInteraction,
    MapDrawControl,
    MapFullScreenControl,
    MapGraticuleLayer,
    MapHeatmapLayer,
    MapImageLayer,
    MapLayerGroup,
    MapLayersControl,
    MapLinkInteraction,
    MapMarker,
    MapMousePositionControl,
    MapOverlay,
    MapOverviewMapControl,
    MapPointerInteraction,
    MapScaleLineControl,
    MapSearchControl,
    MapSelectInteraction,
    MapTileLayer,
    MapTranslateInteraction,
    MapVectorLayer,
    MapView,
    MapWebGLTileLayer,
} from "../../lib/openlayers";
import MapBase from "./Map";

// Everything a map can be built from, hung off the map itself, since what they are written
// inside is the only place any of them does anything. They are handed on from the OpenLayers
// wrapper rather than wrapped again: each is already the piece it says it is, and a map that
// re-dressed them would be a second library rather than a way into this one
export const Map = Object.assign(MapBase, {
    View: MapView,
    Marker: MapMarker,
    Overlay: MapOverlay,
    LayerGroup: MapLayerGroup,
    TileLayer: MapTileLayer,
    ImageLayer: MapImageLayer,
    VectorLayer: MapVectorLayer,
    GraticuleLayer: MapGraticuleLayer,
    HeatmapLayer: MapHeatmapLayer,
    WebGLTileLayer: MapWebGLTileLayer,
    AttributionControl: MapAttributionControl,
    DrawControl: MapDrawControl,
    FullScreenControl: MapFullScreenControl,
    LayersControl: MapLayersControl,
    MousePositionControl: MapMousePositionControl,
    OverviewMapControl: MapOverviewMapControl,
    ScaleLineControl: MapScaleLineControl,
    SearchControl: MapSearchControl,
    DragRotateAndZoomInteraction: MapDragRotateAndZoomInteraction,
    LinkInteraction: MapLinkInteraction,
    PointerInteraction: MapPointerInteraction,
    SelectInteraction: MapSelectInteraction,
    TranslateInteraction: MapTranslateInteraction,
});

export {
    MapView,
    MapMarker,
    MapOverlay,
    MapLayerGroup,
    MapTileLayer,
    MapImageLayer,
    MapVectorLayer,
    MapGraticuleLayer,
    MapHeatmapLayer,
    MapWebGLTileLayer,
    MapAttributionControl,
    MapDrawControl,
    MapFullScreenControl,
    MapLayersControl,
    MapMousePositionControl,
    MapOverviewMapControl,
    MapScaleLineControl,
    MapSearchControl,
    MapDragRotateAndZoomInteraction,
    MapLinkInteraction,
    MapPointerInteraction,
    MapSelectInteraction,
    MapTranslateInteraction,
};
export { DEFAULT_MAP_LATITUDE, DEFAULT_MAP_LONGITUDE, DEFAULT_MAP_ZOOM } from "./Map";
export { useMap, getAddress, getLonLat, DEFAULT_MARKER_COLOR } from "../../lib/openlayers";
export type {
    MapViewProps,
    MapMarkerProps,
    MapOverlayProps,
    MapOverlayContent,
    MapLayerProps,
    MapLayerGroupProps,
    MapTileLayerProps,
    MapImageLayerProps,
    MapVectorLayerProps,
    MapGraticuleLayerProps,
    MapHeatmapLayerProps,
    MapWebGLTileLayerProps,
    MapAttributionControlProps,
    MapCustomControlProps,
    MapDrawControlProps,
    MapDrawShape,
    MapFullScreenControlProps,
    MapLayersControlProps,
    MapMousePositionControlProps,
    MapOverviewMapControlProps,
    MapScaleLineControlProps,
    MapSearchControlProps,
    MapSearchResult,
    MapDragRotateAndZoomInteractionProps,
    MapLinkInteractionProps,
    MapPointerInteractionProps,
    MapSelectInteractionProps,
    MapTranslateInteractionProps,
} from "../../lib/openlayers";
export * from "./Map.types";
